# Generated by Django 5.2.10 on 2026-04-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_attendance_dailytask_dailyupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='completed',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.domain'),
        ),
    ]
