# Generated by Django 5.2.10 on 2026-04-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_dailytask_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dailyupdate')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='accounts.student')),
            ],
        ),
    ]
