# Generated by Django 5.2.10 on 2026-04-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_student_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='role',
            field=models.CharField(choices=[('college', 'College Mentor'), ('industry', 'Industry Mentor')], default='none', max_length=20),
            preserve_default=False,
        ),
    ]
