# Generated by Django 5.2.10 on 2026-04-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_dailytask_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.domain'),
        ),
    ]
