# Generated by Django 5.2.10 on 2026-04-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_mentor_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.college'),
        ),
    ]
